version: '3.8'

services:
  app:
    image: devops-exercise 
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - BUNDLE_DEPLOYMENT=${BUNDLE_DEPLOYMENT}
      - BUNDLE_PATH=${BUNDLE_PATH}
      - BUNDLE_WITHOUT=${BUNDLE_WITHOUT}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    networks:
      - app-network
    command: sh -c "./bin/rails db:migrate && bundle exec puma -C config/puma.rb"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/localhost.crt:/etc/nginx/certs/localhost.crt:ro
      - ./nginx/certs/localhost.key:/etc/nginx/certs/localhost.key:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge